# May 18, 2023 - NAS
# in Version 2 we are adding the TOF3 < 20 ns criterion
#!/usr/bin/python
import numpy as np
import argparse
from scipy.optimize import curve_fit
import random
import datetime
from spacepy.pycdf import CDF
import pandas as pd
import os
from pathlib import Path

PI = np.pi

# ESA Steps
nesa = 7
nalpha = 40
nphi = 3600
dang = 0.1 * PI /180.0
deg = 6.0
nra = 60
ncolat = 30
nmap = nra*ncolat*nesa


def argParsing():

    parser = argparse.ArgumentParser(
        description=(
            "This tool accepts the histogram count and exposure distribution from csv file and create 30x60 csv maps"
        )
    )

    parser.add_argument(
        '-de', '--defiledir',
        required=True,
        help='Path to the location of CSV files generated by flight_to_csv.py'
    )
    
    parser.add_argument(
        '-se', '--start_esa',
        required=False,
        type = int,
        help='Start ESA Number'
    )
    
    parser.add_argument(
        '-ee', '--end_esa',
        required=False,
        type = int,
        help='End ESA Number'
    )
                           
                        
    return parser.parse_args()



eff_h = 1.0

esa_energy = {
    1: 0.016,
    2: 0.030,
    3: 0.056,
    4: 0.106,
    5: 0.200,
    6: 0.405,
    7: 0.787,
    8: 1.821
}

gf = {
    1: 7.0e-5,
    2: 7.9e-5,
    3: 9.7e-5,
    4: 11.2e-5,
    5: 14.0e-5,
    6: 17.7e-5,
    7: 22.5e-5,
    8: 6.721e-5
}

ox_gf = {
    1: 3.54757e-05,
    2: 3.98436e-05,
    3: 6.36456e-05,
    4: 7.28599e-05,
    5: 7.23832e-05,
    6: 6.88855e-05,
    7: 8.00573e-05,
    8: 7.79902e-05,
}


# based on Nov 8-9 measurements
bg_rate = {
    1: 0.000167138,
    2: 0.000174735,
    3: 0.000220318,
    4: 0.000197526,
    5: 0.000258304,
    6: 0.000113958,
    7: 0.000189929
}

# args = argParsing()

# el = args.element if args.element else "Hy"

# work_dir1 = args.defiledir
# start_day = args.start_yeardate
# end_day = args.end_yeardate
# start_esa = args.start_esa
# end_esa = args.end_esa

for pp in [75,90,105]:
    work_dir1 = f'./outdir/pivot_{pp}/daily'
    map_dir = f"./outdir/pivot_{pp}/maps/"
    
    os.makedirs(map_dir, exist_ok=True)
    
    data_dir = Path(work_dir1)
    
    print(f"Making Maps for Pivot {pp}")
    
    for esa in range(1,8):
    
        print(esa)
        h_cnts_map = np.zeros((30,60))
        h_rate_map = np.zeros((30,60))
        h_flux_map = np.zeros((30,60))
        h_func_map = np.zeros((30,60))
        h_fvar_map = np.zeros((30,60))
        exposure = np.zeros((30,60))
        background = np.zeros((30,60))
        back_map = np.zeros((30,60))
        back_rate_map = np.zeros((30,60))
        stonoise = np.zeros((30,60))
        h_rate_unc = np.zeros((30,60))
        h_rate_var = np.zeros((30,60))
    
        for filepath in data_dir.glob(f'*esa{esa}.csv'):
        # for yd in range(start_day,end_day+1):
        #     sk = ''
        #     file = work_dir1 + f"/data_YD_{yd}_esa{esa}.csv"
            file = str(filepath)
            # if not os.path.exists(file):
            #     print("No file")
            #     continue
            df = pd.read_csv(file)
            ps_ra = df['ra'].values
            ps_dec = df['dec'].values
            counts = df['counts'].values
            expo = df['expo'].values
            
            for ia in range(0, 60):
                    ra = ps_ra[ia]
                    dec = ps_dec[ia]
                    
                    theta = 90.0 + dec
                    
                    imap = int(ra/deg)
                    if (imap == 60):
                        imap = 0
                    jmap = int(theta/deg)
                    if (jmap == 30):
                        # jmap = 29
                        jmap = 0
                    
                    h_cnts_map[jmap,imap] += counts[ia]
                    exposure[jmap,imap] += expo[ia]
                    
        for imap in range(0, nra):
            for jmap in range(0,ncolat):
                
                expo = exposure[jmap,imap]
                energy = esa_energy[esa]
                # if el == 'Hy':
                #     geo = gf[esa]
                #     brate = bg_rate[esa]
                # else:
                #     geo = ox_gf[esa]
                
                geo = gf[esa]
                brate = bg_rate[esa]
                
                if (expo > 0.0):
                    back_rate_map[jmap,imap] = background[jmap,imap]
                    h_rate_map[jmap,imap] = h_cnts_map[jmap,imap] / expo
                    h_flux_map[jmap,imap] = h_rate_map[jmap,imap] / (geo * energy)
                    back_map[jmap,imap] = background[jmap,imap] / (geo * energy)
                    h_rate_unc[jmap,imap] = np.sqrt( h_cnts_map[jmap,imap] )/expo
                    h_rate_var[jmap,imap] = h_rate_unc[jmap,imap]**2
                    if (brate > 0.0):
                        stonoise[jmap,imap] = h_rate_map[jmap,imap] / ( brate )
                    if (h_cnts_map[jmap,imap] > 1.0):
                        h_func_map[jmap,imap] = h_flux_map[jmap,imap] / np.sqrt( h_cnts_map[jmap,imap] )
                        h_fvar_map[jmap,imap] = h_func_map[jmap,imap]*2
                    else:
                        h_func_map[jmap,imap] = 0.0
                        h_fvar_map[jmap,imap] = 0.0
                        
        
        sbg_file = pd.DataFrame(stonoise)
        sbg_file.to_csv(map_dir+f"/map_stbg_esa{esa}.csv", index=False)
        
        expo_file = pd.DataFrame(exposure)
        expo_file.to_csv(map_dir+f"/map_expo_esa{esa}.csv", index=False)
        
        cnts_file = pd.DataFrame(h_cnts_map)
        cnts_file.to_csv(map_dir+f"/map_cnts_esa{esa}.csv", index=False)
        
        rate_file = pd.DataFrame(h_rate_map)
        rate_file.to_csv(map_dir+f"/map_rate_esa{esa}.csv", index=False)
        
        flux_file = pd.DataFrame(h_flux_map)
        flux_file.to_csv(map_dir+f"/map_flux_esa{esa}.csv", index=False)
        
        func_file = pd.DataFrame(h_func_map)
        func_file.to_csv(map_dir+f"/map_func_esa{esa}.csv", index=False)
        
        rate_unc_file = pd.DataFrame(h_rate_unc)
        rate_unc_file.to_csv(map_dir+f"/map_runc_esa{esa}.csv", index=False)
        
        h_rate_var_file = pd.DataFrame(h_rate_var)
        h_rate_var_file.to_csv(map_dir+f"/map_rvar_esa{esa}.csv", index=False)
        
        h_fvar_map_file = pd.DataFrame(h_fvar_map)
        h_fvar_map_file.to_csv(map_dir+f"/map_fvar_esa{esa}.csv", index=False)
    
        # func_file = pd.DataFrame(h_func_map)
        # func_file.to_csv(f"2009_lo_maps/2009_lo_map_func_{esa}_{el}.csv", index=False)
        
        # back_file = pd.DataFrame(back_map)
        # back_file.to_csv(f"2009_lo_maps/2009_lo_map_back_{esa}_{el}.csv", index=False)
        
        # backrate_file = pd.DataFrame(back_rate_map)
        # backrate_file.to_csv(f"2009_lo_maps/2009_lo_map_backrate_{esa}_{el}.csv", index=False)
